export const faq = `
SYSTEM DEFINITIONS: FREQUENTLY ASKED QUESTIONS (FAQ)

--- MATCH RESOLUTION & HOW THE GAME WORKS ---

Q: How are matches actually resolved?
A: Two automated league bots are randomly selected and each independently picks a move: ROCK, PAPER, or SCISSORS. The moves resolve using standard rules (Rock crushes Scissors, Scissors cuts Paper, Paper covers Rock), and the bot with the winning move is declared the match winner. As a Predictor, you do not play any moves yourself; you watch the match and bet on which side you think will win.

Q: Why do I not pick ROCK, PAPER, or SCISSORS myself?
A: You are a Predictor, not a Player. The bots are the ones competing in the match. Your role is to forecast which bot will win and wager virtual points on that outcome.

Q: Can matches end in a tie?
A: No. The match generator guarantees that the two bots always produce different moves, so every match has a clear winner and payouts are always immediate.

Q: Is there any skill involved in predicting?
A: Because both bots select moves randomly and independently, every match is a 50/50 coin flip at the point of prediction. No move history, bot name, or previous result carries predictive value. The Bonus system, Flash Events, Global Events, Relics, and Win Streaks are the mechanisms that differentiate long-term Predictor outcomes, not prediction accuracy on any individual match.

Q: What is the house edge?
A: The asymmetric payout structure creates a built-in house edge. A correct prediction returns +100% of the wager while an incorrect prediction costs -50% of the wager. On a 50/50 match the expected value per unit wagered is slightly negative before bonuses. The Bonus system, event modifiers, and relic effects can offset or reverse this edge in the short term.

Q: What is my starting balance?
A: All new Predictors begin with 200,000 points. Points can never drop below a floor of 100,000 regardless of losses.

Q: What is the demo traffic I see in the live feed?
A: The live feed shows a mix of real user bets and simulated demo traffic generated by the system. Demo traffic exists to keep the activity feed populated and visually active during low-concurrency periods. It has no effect on your bets, your balance, or any game systems.

--- ACCOUNT, IDENTITY, AND NICKNAMES ---

Q: Are accounts bound to email addresses or social logins?
A: No. Accounts use a zero-friction local browser setup where your profile is generated and stored locally in your browser. Returning users are loaded automatically, bypassing any sign-up or login screens.

Q: How can I change my nickname, and what are the rules?
A: There is no manual text entry for nicknames. The only way to change your nickname is by clicking the Reroll or Randomize button in your profile settings. Nicknames are entirely generated by the system to maintain unique identities across the league.

Q: How can I migrate my profile to another device or restore lost data?
A: During your first visit, the onboarding flow introduces a unique recovery code. Copying this code allows you to migrate or restore your points, streaks, relics, and achievements on another device by entering it in your profile settings.

Q: What happens if I clear my browser data without a recovery code?
A: If your browser local data is cleared before saving your recovery code, progress is permanently lost. The main developer cannot manually restore or rebuild un-linked profiles since no personal data is captured.

Q: How do LinkedIn integrations work on public profiles?
A: You can link a valid LinkedIn profile in your settings. This adds a verified badge next to your name on public profiles and leaderboards, letting others click through to your professional profile.

Q: What does the DEV badge mean next to certain usernames on the leaderboard?
A: The DEV badge is an exclusive marker reserved solely for the main developer on the leaderboards.

--- GAMEPLAY, ODDS, AND THE BETTING WINDOW ---

Q: What are the exact timing rules for betting?
A: Matches run continuously on a 5-second loop. You have a 3-second window at the start of each match cycle to place your bet before the round locks.

Q: How do payouts and losses work?
A: A correct prediction wins you +100% of your wagered bet amount. An incorrect prediction loses exactly 50% of your wagered bet amount, and the remaining 50% of that wager is returned back to your balance.

Q: Is there a minimum point limit?
A: Yes. Your balance can never drop below a floor of 100,000 points. If a loss pushes you below this limit, your points are automatically restored to the 100,000 floor.

--- LEADERBOARD MECHANICS AND SORTING ---

Q: What is the difference between Laps and Achievements on the leaderboards?
A: The Laps and Speedrun tabs track how many prestige ascensions you have completed and the speed of those runs measured by the fewest bets taken. The Achievements tab ranks predictors purely on their absolute count of unlocked achievements.

Q: How often do the daily and weekly leaderboards reset?
A: Daily leaderboards reset automatically at 00:00 UTC, clearing daily gains and daily peak milestones for a fresh start. Weekly leaderboards reset on a rolling 7-day cycle, while All-Time leaderboards are permanent.

Q: How does the mobile leaderboard fit data on small screens?
A: On smaller mobile screens, the wide leaderboard table collapses into a dense vertical layout. This keeps wins, losses, points, gains, and peaks readable without requiring horizontal scrolling.

Q: Does ascending remove me from the all-time leaderboard?
A: No. Your all-time peak point value is permanently recorded and determines your All-Time leaderboard position. Ascending resets your active balance but does not erase your historical peak.

Q: What does the GAIN column show on the leaderboard?
A: The GAIN column shows your net point change over the currently selected time filter (Daily, Weekly, or All-Time). A positive green value means you gained more than you lost in that period.

Q: How is the Speedrun leaderboard ranked?
A: Speedrun ranks are determined by the fewest number of bets taken to complete a single Ascension cycle reaching 999 STR from a starting balance. Lower bet counts rank higher. Only completed laps count toward this ranking.

--- WIN STREAK ENGINE ---

Q: What are the win streak tiers and multipliers?
A: Consecutive win streaks unlock multiplier tiers: 3 wins (x2), 4 wins (x3), and 5 or more wins (x5).

Q: How long does the x5 streak multiplier last?
A: The x5 multiplier remains active on all subsequent correct predictions until you make an incorrect prediction, which breaks your streak and resets the multiplier to x1.

Q: Does my win streak change how the game looks?
A: Yes. Reaching higher streak tiers triggers real-time visual themes that shift the colors, borders, and glows of the active betting controls.

Q: What happens to my win streak during the Fever Festival?
A: During the Fever Festival, losses do not reset your win streak and your streak multiplier tier is frozen in place for the duration regardless of match outcome. Your streak counter and visual theme both remain at their current state even on a loss.

Q: What happens to my win streak during Sanguine Festival if I am already at x5?
A: Sanguine forces all predictions to resolve as wins, so your streak continues incrementing normally. If you are already at x5 it remains at x5 since that is the maximum tier. The only exception is if you bet against the Daily Oracle Prophecy, in which case the Oracle override causes a loss and your streak resets normally.

Q: Does my win streak reset when I ascend?
A: Yes. Ascending resets your point balance to 200,000 and your active win streak resets to zero. Your all-time longest streak record in your profile stats is preserved permanently.

Q: Does Cyclone Blitz affect my streak if I lose during the event?
A: No. The Streak Turbocurrent only applies to wins, granting +2 streak progress instead of +1. A loss during Cyclone Blitz still breaks your streak and resets it to zero exactly as normal.

--- THE BONUS AND PITY SYSTEM ---

Q: What is the random Bonus system?
A: Each match has a 40% chance to trigger a random Tiered Bonus multiplier, which scales up your payouts on wins and heavily cushions point losses if you predict incorrectly.

Q: What is the Pity System and how does it guarantee bonuses?
A: If a bonus does not trigger naturally within 3 consecutive matches, the system guarantees a bonus on your 4th match, ensuring you are never left without a bonus opportunity for long.

Q: Does the Resonance Festival affect the bonus pity counter?
A: Resonance guarantees a Common or Rare bonus on every prediction for its duration, which means the pity counter never needs to fire while Resonance is active. The pity counter does not accumulate during Resonance since a bonus triggers on every match.

Q: Does the bonus pity counter reset on ascension?
A: Yes. The pity counter is a session-level mechanic tied to your current betting run and resets when your balance resets on ascension.

--- THE RELIC CORE ---

Q: How do relics drop, and can I get duplicates?
A: Relics drop randomly after completed predictions. The system features duplicate protection, meaning once you find a specific relic it is removed from the drop pool so you never receive a duplicate.

Q: What is the rule regarding switching relics mid-match?
A: Flash Event values and multipliers are locked the moment an event begins. Equipping a relic after an event starts will not change its values. Additionally, progress on charge-up relics such as those counting consecutive wins pauses and resets if you unequip them.

Q: How do completed Laps affect my relic drop rates?
A: Each completed prestige Lap permanently increases your base drop rates for all relic rarities up to a set maximum cap.

Q: How many relics are there in total?
A: There are 17 unique relics across five rarity tiers: 3 Common, 6 Rare, 2 Epic, 3 Legendary, and 3 Mythical. Owning all 17 is tracked by the Full House achievement.

Q: What happens if a relic drops while a Flash Event is active?
A: The relic is added to your inventory immediately and you can equip it or dismiss the popup. However due to the Anti-Swap Protocol, equipping a relic after a Flash Event has already started will not apply that relic's Flash Event bonuses to the current event. The relic effect will apply normally from the next event onwards.

Q: Do my relics reset when I ascend?
A: No. Your full relic collection including equipped relic and all discovered relics persists through ascension. Relics are permanent account-level items and are never reset by a Chrono-Lap.

Q: Which charge-up relics reset their progress counter if unequipped?
A: The Buffer Module (every 15 matches, next loss does not reset streak), the Kinetic Capacitor (every 30 wins, next win gains x2 multiplier), and the Logic Gate (every 20 wins, next win guarantees Legendary bonus) all pause and reset their stored progress counters when unequipped.

--- EVENTS, SHADERS, AND PLAYER FESTIVALS ---

Q: What is the difference between Global Events, Flash Events, and Festivals?
A: Global Events are server-wide scheduled gameplay storms for all players simultaneously. Flash Events are personal modifiers with a 5% trigger chance per bet lasting 3 predictions. Festivals are globally-broadcast events triggered by specific player milestone actions such as high streaks, big multipliers, or lap completions.

Q: Can two Global Events be active at the same time?
A: No. Only one Global Event can be active at any time and they do not stack. The system enforces a strict sequential loop: one event completes, a cooldown runs, then the next event is selected. There is no queuing mechanism.

Q: Can two Flash Events be active at the same time?
A: No. A personal Flash Event occupies your event slot for its 3-match duration. A new Flash Event cannot trigger while one is already active. The Spark Festival is the only mechanism that can refill your remaining Flash Bets to 3 while an event is already running.

Q: Can a Festival and a Flash Event be active at the same time?
A: Yes. Both can be active simultaneously. If they are, Flash Event UI theming takes visual priority over the Festival theme on your screen.

Q: Can two Festivals be active at the same time?
A: No. Only one Festival can be active globally at any time. Triggers that occur during an active Festival or its cooldown are discarded entirely. There is no queue.

Q: Do Global Event modifiers stack with Flash Event multipliers?
A: Yes. When both a Global Event and a personal Flash Event are active simultaneously their modifiers apply together. For example a 3x Flash Event multiplier and a Solar Flare 2x multiplier both apply to the same win, compounding the total payout.

Q: Does the Ghost Festival echo apply on top of Flash Event multiplied wins?
A: Yes. The Ghost Festival applies a 1.2x echo to the final resolved payout, meaning it multiplies the already-boosted Flash Event win rather than applying to the base bet amount.

Q: Does Tidal Surge apply before or after my streak multiplier?
A: The +20% Win Echo from Tidal Surge applies to the final calculated payout, stacking on top of streak multipliers, bonus multipliers, and relic effects rather than replacing them.

Q: Can The Architect's Keystone produce a Mythical bonus tier during the Resonance Festival?
A: No. The Resonance Festival caps all bonus rolls at Rare and any roll that would exceed Rare is recalculated downward. The Architect's Keystone upgrades the triggered bonus tier, but Resonance's cap applies at the resolution layer, preventing any Epic or higher outcome during Resonance's active window.

Q: If I trigger a Spark Festival while already in a Flash Event, do I get a new event or a refill?
A: You get a refill. If you are already in a Flash Event when Spark triggers, your remaining Flash Bets are topped back up to 3 rather than starting a new separate event.

Q: Does the Safeguard Festival affect the 100,000 point floor mechanic?
A: No. The floor is an independent system and always applies regardless of any active Festival. Safeguard only reduces the loss deduction rate from 50% to 40% of your stake; the 100,000 point floor remains in effect on top of that.

Q: What does the Safeguard Festival reduce losses to exactly?
A: During Safeguard, losses deduct 40% of your wagered stake instead of the standard 50%. The remaining 60% is returned to your balance rather than the usual 50%.

Q: What happens if I complete a Lap while the Fever Festival is active?
A: The Surge Festival trigger on Lap completion is discarded because Fever is already occupying the active Festival slot and the 5-minute cooldown follows every Festival conclusion. The Surge trigger does not queue; it is lost entirely.

Q: What happens when a Global Event is about to start?
A: A warning marquee will populate at the top of the screen, and the Oracle Voice will read out countdown warnings at 60 and 30 seconds remaining.

Q: What is the Win Echo Protocol during Tidal Surge?
A: Correct predictions during a Tidal Surge event receive an automatic +20% bonus payout on top of all other multipliers.

Q: What does Solar Flare do?
A: During an active Solar Flare, all successful predictions receive a flat 2.0x payout multiplier. The interface shifts into a star-white plasma and deep lavender corona visual state with expanded bloom filters and rotating lens flares.

Q: What is the Streak Turbocurrent during Cyclone Blitz?
A: Successful predictions increase your win streak by +2 instead of +1, letting you reach high-tier streak multipliers twice as fast. Losses during Cyclone Blitz still break your streak normally.

Q: What is the Variable Echo Field during Mirage Cataclysm?
A: Successful predictions award a random extra payout between 15% and 50% of your calculated winnings on top of all other modifiers.

Q: What triggers a Player Festival, and what is the cooldown?
A: Major milestones like high-tier win streaks, big multipliers, relic discoveries, or completing a prestige Lap broadcast a global Festival state to all connected active players. Once a Festival ends, a strict 5-minute cooldown locks out new triggers.

Q: What is the Sanguine Festival?
A: Triggered when a predictor hits a 4-loss streak (100%), it corrects all predictions to resolve as wins for 15 seconds covering 3 matches. If you bet against the Daily Oracle Prophecy you will still lose, as the Oracle overrides all absolute win corrections.

Q: What is the Surge Festival?
A: Triggered when a predictor completes a Chrono-Lap (100%), the Surge Festival applies a 2x global multiplier to all win payouts for 30 seconds covering 6 matches for every active player.

Q: What is the Fever Festival?
A: Triggered by a 5-win streak (20% chance) or an 8-win streak (100%), the Fever Festival freezes your win streak multiplier for 30 seconds covering 6 matches. Losses do not reset your streak for the duration.

Q: What is the Ghost Festival?
A: Triggered by a total win multiplier of 30x or higher (40% chance) or 60x or higher (100%), the Ghost Festival adds a 20% Win Echo to all wins for 1 minute covering 12 matches. A ghostly echo value visually drifts off the result number in the UI after each win.

Q: What is the Vault Festival?
A: Triggered by discovering a Mythical Relic (100%), the Vault Festival doubles all Relic drop rates for all players for 2 minutes covering 24 matches.

Q: What is the Safeguard Festival?
A: Triggered by completing a Mythical Achievement (100%) or a Legendary Achievement (50%), Safeguard reduces loss deductions by 20% for 1 minute covering 12 matches. Losses deduct 40% of the stake instead of the standard 50%.

Q: What is the Resonance Festival?
A: Triggered by 3 tiered bonuses in a row (100%) or a Legendary Bonus (30% chance), Resonance guarantees a Common or Rare bonus on every prediction for 40 seconds covering 8 matches. Epic and Legendary bonus rolls are recalculated downward to Rare for the duration.

Q: What is the Spark Festival?
A: Triggered by completing 2 Flash Events in a row (100%) or hitting a Legendary or Mythical Bonus during a Flash Event (100%), Spark instantly gives all active players a fresh Flash Event with 3 Flash Bets. Players already in a Flash Event have their remaining bets refilled to 3. The Spark window lasts 45 seconds; Flash Events granted by Spark expire at the end of that window.

--- THE DAILY ORACLE PROPHECY ---

Q: How does the Daily Oracle Prophecy work?
A: Once per day you can consult the Oracle for a guaranteed side. Following the Oracle choice rigs the outcome in your favor, while betting against it results in a guaranteed loss regardless of the actual match result or any active Festival correction effects.

Q: What happens if I bet against the Oracle during Sanguine Festival?
A: The Oracle override takes precedence over all correction protocols. Even though Sanguine forces all predictions to resolve as wins, betting against the Oracle pick still results in a loss.

Q: Does the Oracle guaranteed side change during the day?
A: No. The Oracle prophecy is generated once per day server-side and is fixed for the full UTC day. It does not change between consultations.

Q: Can I get extra Oracle attempts by clearing my browser cache?
A: No. Oracle usage and streaks are securely tracked on the server and bound to your account code. Clearing local data will not grant extra attempts.

Q: Can the Oracle tell me which side will win the next match?
A: No. The Daily Prophecy is the only mechanism for guaranteed outcome guidance and is available once per day. For all other matches both sides have equal probability and the Oracle cannot forecast individual match outcomes.

Q: Can I ask the Oracle about future content or upcoming features?
A: The Oracle has no access to classified development roadmaps or unreleased system parameters. Future content remains locked to preserve simulation integrity.

--- IDLE AUTO-BET ---

Q: Can idle auto-bet trigger Flash Events?
A: Yes. Auto-bet places real bets on your behalf and is treated identically to manual bets by all game systems, including the 5% Flash Event trigger chance per prediction.

Q: Does idle auto-bet place bets during an active Flash Event?
A: Yes. Auto-bet continues placing bets during Flash Events and those bets consume your remaining Flash Bets normally. The Flash Event resolves across whichever predictions auto-bet places next.

Q: Can I use auto-bet during a Global Event?
A: Yes. Auto-bet is fully compatible with all active Global Events. Event modifiers apply to auto-bet resolved predictions exactly as they would to manual bets.

--- ASCENSION AND PROGRESSION PERSISTENCE ---

Q: Do my achievements reset when I ascend?
A: No. All earned achievements and badge selections persist through ascension. The Achievement Codex is a permanent account record and is never reset by a Chrono-Lap.

Q: Do my unlocked visual tier styles reset when I ascend?
A: No. Any visual point tier styles previously unlocked based on your all-time peak remain permanently available in your profile settings. This is called Persistent Mastery and is a core part of the Ascension system design.

--- SAFETY, PRIVACY, AND HARDWARE ---

Q: Does the application track my physical location or IP?
A: No. During account creation the system determines an approximate city and country to help understand where players are joining from. This is done entirely locally and offline. Raw IP addresses are anonymized immediately and public audit logs display masked subnets only.

Q: What is the single-tab guard?
A: The app runs automated browser checks to detect duplicate open tabs. If multiple tabs are open at once it automatically shuts down redundant live-feed connections and displays a warning to protect your account from rate-limiting penalties.

Q: Why will this app not load on my older phone or tablet?
A: The application utilizes large-number calculations to manage compounding multipliers and massive point values without losing precision. Older mobile devices and browsers lacking support for these calculations cannot process the game math.

Q: How do I report bugs or submit feedback?
A: You can open the feedback portal directly in the interface. It automatically bundles basic visual settings and supports pasting screenshots directly from your clipboard to help the developer fix issues.

--- BONUS TIER SYSTEM DETAIL ---

Q: What are the exact bonus multiplier ranges for each tier on a win?
A: Common bonuses multiply the win payout by 1.5x to 2.2x. Rare bonuses multiply by 2.2x to 3.2x. Epic bonuses multiply by 3.2x to 4.2x. Legendary bonus applies a flat 5x multiplier. Mythical bonus applies a flat 7x multiplier.

Q: What do bonus tiers do when I lose a prediction?
A: On a loss, bonus tiers reduce the amount deducted from your balance. Common and Rare bonuses reduce the loss to somewhere between 75% and 25% of your stake. Epic bonuses reduce the loss further. A Legendary bonus fully negates the loss, meaning you lose zero points on that prediction. A Mythical bonus also fully negates the loss and is the highest possible outcome.

Q: Does a Legendary or Mythical bonus completely cancel a loss?
A: Yes. Both Legendary and Mythical bonus tiers fully negate a loss, reducing the point deduction to zero. You keep your entire wagered amount even on an incorrect prediction.

Q: What is the Mythical bonus tier unlocked by The Architect's Keystone relic?
A: The Architect's Keystone unlocks a special x15 Mythical bonus tier that is not available through normal rolls. It visually features crimson bloom, instability flicker, red particle eruptions, and heavy motion trails. This tier can only appear when the Keystone upgrades a triggered Legendary bonus to the next rarity.

--- ACHIEVEMENT SYSTEM DETAIL ---

Q: How many achievement badges can I display on my profile and leaderboard?
A: You have 5 dedicated badge slots on your public profile and leaderboard row. You can fill these with any combination of earned achievements or the optional LinkedIn social badge.

Q: Can I choose which badges to display?
A: Yes. You can curate your 5 badge slots from any achievements you have earned. Selecting your displayed badges is done from your profile settings. Your selection is mirrored globally on the leaderboard.

Q: How does the dynamic badge upgrading system work?
A: When you earn a higher rarity tier of a chained achievement, it automatically replaces the lower tier version in your inventory. For example earning the Rare win streak badge automatically removes the Common version. This keeps your badge collection focused on your highest accomplishments.

Q: How many total achievements are there?
A: There are over 100 achievements across 15 distinct categories, ranging from win volume and streaks to relic collection, event participation, Oracle mastery, and special hidden milestones.

--- RELIC STACKING AND INTERACTION ---

Q: Does the Scavenger's Lens relic stack with the Vault Festival drop rate doubling?
A: These are separate systems that both affect acquisition rate. The Vault Festival doubles the base drop rates for all relics for all players. The Scavenger's Lens adds a 20% acquisition rate boost on top of that for the equipped player. Both effects apply independently.

Q: Does the Cobalt Core relic boost all four Flash Event types equally?
A: Yes. The Cobalt Core increases your overall Flash Event appearance rate by 25%, applying uniformly across all event types rather than boosting any single theme.

Q: Can I equip a relic and immediately benefit from it mid-session?
A: Yes for most effects, with one exception. Passive relics like Precision Bearing, Conductive Filament, and Prismatic Shard apply immediately on equip. Flash Event bonuses from relics like Lunar Siphon or Overdrive Relay only apply to events that trigger after the relic is equipped, due to the Trigger Snapshot rule locking event values at the moment of activation.

--- FLASH EVENT SYSTEM DETAIL ---

Q: Does the 5% Flash Event chance apply per bet or per match?
A: It applies per bet placed. Each time you place a prediction you have a 5% independent chance of triggering a Flash Event on that bet. Not betting a match means no roll occurs for that cycle.

Q: What happens at the end of a Flash Event if I have bets remaining?
A: If a Flash Event ends due to the Spark Festival 45-second window expiring while you still had Flash Bets remaining, those bets are consumed by the expiration. Flash Events earned independently of Spark always run their full 3 predictions regardless.

Q: What is the weighted selection for Flash Events?
A: Event selection is weighted to support controlled rollout of seasonal themes. This means some events may appear more frequently than others without changing the global 5% trigger rate.

--- LIVE FEED AND ACTIVITY ---

Q: What is the live activity feed?
A: The live feed displays a continuous stream of match results and bet outcomes in real time including your own bets with instant feedback, other active players bets, and simulated demo traffic to maintain activity during low-concurrency periods. Your bets are always injected at the front of the feed with zero delay.

Q: What are the live league stats shown on the ticker?
A: The stat ticker updates every 15 seconds and displays the daily total betting volume across all predictors, the net community point gains for the day, and the current Daily MVP (the predictor with the highest gains that day).

--- PROFILE AND STATISTICS ---

Q: What are the 16 tracked data points on a player profile?
A: Profiles surface joined date, longest recorded streak, lap count, live placement across Daily Weekly and All-Time leaderboards, peak balance, daily high, weekly high, total gained, total risked, biggest single win, highest multiplier achieved, win rate, max streak, total wins, total losses, and bonus telemetry including pity triggers and bonus tier history.

Q: What is the match history system on profiles?
A: Each profile includes a full interactive match history organized into three tabs: Recent for chronological activity, Biggest Wins for highest-value outcomes ranked, and Best Multipliers for peak bonus and flash event combinations. The system uses infinite scrolling with progressive loading to handle large datasets.


--- LIVE SERVICE STATUS ---

Q: Is the game still being updated?
A: Yes. RPS League is a live-service game with ongoing seasonal content updates introducing new achievements, events, relics, and gameplay systems over time.

Q: How often are updates released?
A: Update cadence is not published on a fixed schedule. Major system additions are documented in the in-app Update History page and surfaced to returning players via the What's New overlay on their next visit.

Q: Are there seasonal events?
A: Yes. Flash Events and Global Events form the continuous event cycle. Seasonal content updates introduce new event types, number tiers, achievements, and gameplay systems as part of the live-service structure.

Q: Will old progress still matter after updates?
A: Yes. Existing relics, achievements, laps, and leaderboard records are preserved through updates. New systems are additive rather than replacing existing progression.

Q: Will my achievements become obsolete?
A: No. The Achievement Codex is a permanent record. New achievements added in updates expand the codex without invalidating previously earned milestones.

`