export const controls = `
SYSTEM DEFINITIONS: USER CONTROLS & INTERFACE
- Point Style Preference: Players can pin any visual tier style they have unlocked based on their historical peak. Setting this to "Auto-Style" dynamically progresses styling as new point scales are crossed.
- Audio Controls Popover: Accessible from the main interface, containing individual toggles for ambient sound effects, a background music (BGM) volume slider, and an independent Arkalon Voice volume slider.
- Arkalon Voice: An in-app synthesis system using the Web Speech API to read prophecies and festival calls at low pitch and slow cadence, simulating a ritual machine.
- Game Systems Popover ("BONUSES" Button): A dedicated interactive button on the right side of the main dashboard, next to the "LOSE: -50%" label. Clicking it launches a comprehensive modal featuring nested accordion panels detailing every core game system, including the Bonus System, Win Streaks, Flash Events, Relic Core, Player Festivals, Global Events, World Bosses, and Neon Paradise.
- Bet Input & Auto-Max Controls: Located above the prediction buttons, this control area contains the Amount input box, a manual "MAX" button, and the "AUTO MAX ON / OFF" toggle. When Auto-Max is enabled, the system automatically resets your active wager to match your full points balance after every single resolved prediction. Turning the toggle on immediately sets your active bet to your maximum current points balance.
- Dedicated Feedback Page: Opened via the "MORE" navigation dropdown, this page allows users to submit categorized messages (Technical Issue, Visuals & Animations, Gameplay & Balance, AI Arkalon Analysis, Suggestion, or General Praise) directly to the developer. The form includes optional name and email inputs, a message text field, and an optional screenshot container supporting native clipboard pasting (Ctrl+V), drag-and-drop, or manual file uploads up to 5MB. Environment metadata and core game state are compiled and attached automatically on submission to assist with trace debugging.

`
