export const BOSS_EFFECT_TEXT: Record<string, string> = {
  HEXURION:
    'HEXURION ACTIVE - STRUCTURAL LATTICE ONLINE - CORRECT PREDICTIONS STRIKE THE BOSS',
  ORPHION:
    'ORPHION ACTIVE - ORBITAL CONVERGENCE LOCKED - CORRECT PREDICTIONS STRIKE THE BOSS',
  FRACTURON:
    'FRACTURON ACTIVE - FRACTAL MATRIX ONLINE - CORRECT PREDICTIONS STRIKE THE BOSS',
  APEXION:
    'APEXION ACTIVE - KINETIC COMPRESSION RISING - CORRECT PREDICTIONS STRIKE THE BOSS'
}

export const BOSS_COLORS: Record<string, string> = {
  HEXURION: '#22d3ee',
  ORPHION: '#a855f7',
  FRACTURON: '#22c55e',
  APEXION: '#f97316'
}
