name: Keep RPS League Awake

on:
  schedule:
    - cron: "*/5 5-16 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping RPS League
        run: |
          sleep $((RANDOM % 60))

          curl -A "Mozilla/5.0 Chrome/130" -s https://rps-league-g275.onrender.com/ > /dev/null
          sleep 30

          curl -A "Mozilla/5.0 Chrome/130" -s https://rps-league-g275.onrender.com/api/matches > /dev/null
          sleep 30

          curl -A "Mozilla/5.0 Chrome/130" -s https://rps-league-g275.onrender.com/api/leaderboard/current > /dev/null
